services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - /var/www/Online-Store-CI-CD/media:/app/media
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - /var/www/Online-Store-CI-CD/media:/app/media
    depends_on:
      - web

volumes:
  static_volume: